### ISSUE TITLE
AttributeError: type object 'QgsMessageBar' has no attribute 'INFO'

### ISSUE THREAD

**Issue by Skipper-is** [austromorph/cartogram3#15]
Fresh install of QGIS3, and tried to run Cartogram 3, but throwing error:

`Traceback (most recent call last):
			  File "C:/Users/skipp/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\cartogram3.py", line 346, in run
			    QgsMessageBar.INFO
			AttributeError: type object 'QgsMessageBar' has no attribute 'INFO'`

Using the Austria example dataset...

**Comment by christophfink** [comment]
Thank you for the bug report! 

This is a change in QGIS’s API (it is undergoing much appreciated refactoring atm), and should be easy to fix. I am travelling from today, though, so please give me a couple of days to release a fixed version.

Note to self: 
Constants moved from individual classes (e.g. QgsMessageBar) to a common Qgis object. 
(cf. https://qgis.org/api/classQgis.html#a60c079f4d8b7c479498be3d42ec96257)

**Comment by christophfink** [comment]
resolved in v3.0.0

**Comment by Skipper-is** [comment]
Yup, works fine! Cheers!
