### ISSUE TITLE
TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'str'

### ISSUE THREAD

**Issue by christophfink** [austromorph/cartogram3#18]
bug report submitted via e-mail:

> When trying to use cartogram I get following message (my data and demo dat)
> Any idea to resolve this ?
>  
> 2018-11-19T13:13:40     WARNING    Traceback (most recent call last):
>               File "C:\[…]/python/plugins\cartogram3\cartogram3.py", line 317, in run
>               self.inputLayer.exportNamedStyle(self.inputLayerStyle, "")
>              TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'str'

**Comment by christophfink** [comment]
Can’t reproduce myself, maybe related to unicode on Windows?
From the [PyQt5 documentation](http://pyqt.sourceforge.net/Docs/PyQt5/gotchas.html#python-strings-qt-strings-and-unicode): 

> If Qt expects a QString then PyQt5 will accept a unicode, a str that contains only ASCII characters, a QByteArray or None.

maybe `None` is acceptable

**Comment by hmeleiro** [comment]
I'm having the same issue in mac.

```
TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'str' 
Traceback (most recent call last):
  File "/Users/meleiro/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cartogram3/cartogram3.py", line 317, in run
    self.inputLayer.exportNamedStyle(self.inputLayerStyle, "")
TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'str'
```

**Comment by christophfink** [comment]
@meneos: Can you try whether the attached version of the plugin works? Install it from 
Plugins → Manage and Install Plugins → Install from ZIP

[cartogram3-3.0.1.zip](https://github.com/austromorph/cartogram3/files/2603341/cartogram3-3.0.1.zip)

**Comment by hmeleiro** [comment]
Now this is the error that I get:

```
Traceback (most recent call last):
  File "/Users/meleiro/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/cartogram3/cartogram3.py", line 317, in run
    self.inputLayer.exportNamedStyle(self.inputLayerStyle, None)
TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'NoneType'
```

**Comment by christophfink** [comment]
@meneos: I was able to reproduce the bug and fix it. 

Release [3.0.1](https://github.com/austromorph/cartogram3/releases/tag/v3.0.1) will be **available from the QGIS plugin repo** as soon as their admins approve my upload. 

Before that, a ZIP file is available from [https://github.com/austromorph/cartogram3/releases](https://github.com/austromorph/cartogram3/releases) for manual installation.

Even though the version numbers are the same, the file from earlier in this thread does _not_ contain the fix (sorry for the version number confusion)

**Comment by hmeleiro** [comment]
Thank you, it works perfectly. Great plugin.
