### ISSUE TITLE
TypeError: QgsMapLayer.exportNamedStyle(): not enough arguments

### ISSUE THREAD

**Issue by NicolasAPESA** [austromorph/cartogram3#19]
Hi, 

When I compute cartogram3 (the version you put on the "TypeError: QgsMapLayer.exportNamedStyle(): argument 2 has unexpected type 'str'" thread) on the austrian data and my own data, I have this error message.

2018-11-26T14:10:47     WARNING    Traceback (most recent call last):
              File "C:/Users/ndevienne/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\cartogram3.py", line 317, in run
              self.inputLayer.exportNamedStyle(self.inputLayerStyle)
             TypeError: QgsMapLayer.exportNamedStyle(): not enough arguments

I tried to understand the code, but I don't read Python ^^

Could you help me ?

**Comment by christophfink** [comment]
Hi @Artlight33

Thanks for the bug report.
This is most likely connected to a recent fix for a new QGIS version – which version are you on? (Please don’t update QGIS yet, so I can try to fix it for previous versions, too)

**Comment by NicolasAPESA** [comment]
3.2.3 - Bonn

**Comment by christophfink** [comment]
Could you try with this version:
[cartogram3-3.0.1b.zip](https://github.com/austromorph/cartogram3/files/2615719/cartogram3-3.0.1b.zip)?
(Install it from
Plugins → Manage and Install Plugins → Install from ZIP)

**Comment by NicolasAPESA** [comment]
It works perfectly ! Thanks a lot

**Comment by christophfink** [comment]
fixed in https://github.com/austromorph/cartogram3/releases/tag/v3.0.2
