### ISSUE TITLE
Plugin crash in Qgis 3.22

### ISSUE THREAD

**Issue by grantime** [austromorph/cartogram3#23]
Hello, I have a problem with the Cartogram plugin in QGIS 3.16.12 , 12 and 13.
 It seems that the grass plugin is the problem. 
In a test with QGIS 3.16.8 with Grass 7.8.5 cortogram works. 
Does the method of calling GRASS change between these versions? 

I also tried to start cartogram from the github master, it does not work.

Sincerely Alexandre Granié

**Comment by DaniloGitH** [comment]
Hello,
I think I have the same problem, in QGIS 3.16.13 or 3.22.1 in Win 10.
The plugin starts to work (I tried with the sample dataset) and arrives at the first iteration and then it does not go on with other iterations and does not produce any result. 
I tried with QGIS 3.16.7 and it works properly 
Thank you in advance
Daniele

**Comment by christophfink** [comment]
Hi Alexandre, hi Daniele!

Thanks for reporting this. I’m suspecting that this is somehow related to #22 (on MacOS). I’ll try to have some time to look into it soon :)

Not sure how GRASS would be involved in it, as cartogram does not use any grass algorithm, but maybe there’s some module loading side effect. Thanks for reporting that, too.

**Comment by lmpedro** [comment]
Hi,

Just reporting that I have a similar problem using 3.22.1 on a Mac. It crashes at the end of the first iteration and then opens some 15 instances of QGIS, with multiple errors.

Thanks!

**Comment by christophfink** [comment]
Could you try whether [this version](https://github.com/austromorph/cartogram3/files/7693578/cartogram3-3.1.0.zip) works? (Install it via the option ‘Install from ZIP’ in the plugin manager) 
Thanks!

**Comment by DaniloGitH** [comment]
Dear Christoph,

thank you, I tried to install it via zip, but this is the error message:
![image](https://user-images.githubusercontent.com/67100718/145618811-49552124-76b8-4c8d-bd29-20f61878ee58.png)

Thank you and best regards
Daniele

**Comment by seancarmody** [comment]
Just upgraded QGIS and successfully installed plugin - will test now.

**Comment by lmpedro** [comment]
Hi Christoph,

Many thanks for this. I installed the plugin (on version 3.22 for Mac), but
still get the same error – programme crashes, opens 15 parallel instances
of it, after first iteration. Let me know if you need more info.

All the best and thanks,
Pedro

**Comment by seancarmody** [comment]
Goes a bit crazy for me too: opens up a lot more QGIS instances, some of which give an error dialogue boxes saying "Update of view in private qgis.db failed database is locked" and errors in the main QGIS screen saying "Invalid Data Source: /--multiprocessing-fork is not a valid or recognized data source."

**Comment by christophfink** [comment]
Thanks for testing, and sorry it did not work (yet).

I have a new version that seems to work well on Windows and Linux, but there’s still some quirks on MacOS which I will try to fix over the next few evenings.

If you’re on Linux or Windows, please test this plugin ZIP: [cartogram3-3.1.0.zip](https://github.com/austromorph/cartogram3/files/7702624/cartogram3-3.1.0.zip)
 
 Thanks!

**Comment by DaniloGitH** [comment]
Dear Christoph, 

thanks in advance for all these efforts!
I tried with QGIS 3.14.14 and 3.22.1, both stand-alone and OSGeo4W installer ​and it works very well and faster than the previous version!
Is it possible to know the problem that you found with this version of QGIS and WIN10? Because I found other problems with this new version of QGIS related to Reference Systems, and I guess if it could be a problem of the new PROJ and/or GDAL libraries

Best regards
Daniele

**Comment by christophfink** [comment]
I’m not 100% sure what to pin it down to, since I changed a lot of things that just were not state-of-the-art anymore. 

Most likely the one change that made most difference is that the plugin now does not operate on QgsGeometry/QgsFeature objects anymore. Memory management, garbage collection, object ownership and the like are slightly complicated in PyQGIS (or so I feel). These objects are coming from the C++ main application, and modifying them in Python is not always straightforward (and moving them between threads is even worse).

**Comment by christophfink** [comment]
Thanks for the patience, @seancarmody, this one now should work also on MacOS (I tested it on an ageing MacBookAir that did not receive updates after Catalina, so can’t be 100% sure). Please report back whether it works for you, so I can release it to the QGIS plugin repository.

[cartogram3-3.1.0.zip](https://github.com/austromorph/cartogram3/files/7706458/cartogram3-3.1.0.zip)

**Comment by lmpedro** [comment]
It works now, many thanks indeed for all the effort! Much appreciated.

**Comment by christophfink** [comment]
Thanks for reporting and testing!

**Comment by DaniloGitH** [comment]
Dear Christoph,

thank you too! Only to let you know that now this new plugin version does not work with QGIS 3.16.11, while with 3.16.14 and 3.22.1 it works very well, but I think it is not a problem because 3.16 will dismiss very soon... but just in case I send you the log:
Best regards
Daniele

2021-12-14T10:48:00     CRITICAL    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\__init__.py", line 34, in classFactory
              from .cartogram3 import Cartogram
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\cartogram3.py", line 9, in 
              from .lib import CartogramUserInterfaceMixIn, CartogramWorkOrchestratorMixIn
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\__init__.py", line 5, in 
              from .cartogramprocessingprovider import CartogramProcessingProvider
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramprocessingprovider.py", line 12, in 
              from .cartogramprocessingalgorithm import CartogramProcessingAlgorithm
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramprocessingalgorithm.py", line 23, in 
              from .cartogramfeatures import CartogramFeatures
              File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramfeatures.py", line 28, in 
              class CartogramFeatures:
              File "C:/Users/danilopc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramfeatures.py", line 125, in CartogramFeatures
              @functools.cache
             AttributeError: module 'functools' has no attribute 'cache'

**Comment by christophfink** [comment]
Thanks for noticing! It seems 3.16.11 comes with Python<3.9 which does not have functools.cache yet ... I’ll restrict the versions, then - thanks!
