### ISSUE TITLE
Plugin does not work on Python < 3.8

### ISSUE THREAD

**Issue by voltameeak** [austromorph/cartogram3#38]
Hi, 
I heard and seen a lot of good things about the cartogram3 plugin, thank you for that. Unfortunately it wasn't possible for me to install it on various machines. I tried it on different PCs, all Win10. 
When I try to install the plugin (doesn't matter which version of the plugin, or QQIS version, I tried 5 different ones, 3.24 down to 3.1). The error message is always the same: 

Konnte Erweiterung 'cartogram3' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

SyntaxError: invalid syntax 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\__init__.py", line 34, in classFactory
    from .cartogram3 import Cartogram
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\cartogram3.py", line 9, in 
    from .lib import CartogramUserInterfaceMixIn, CartogramWorkOrchestratorMixIn
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\__init__.py", line 5, in 
    from .cartogramprocessingprovider import CartogramProcessingProvider
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramprocessingprovider.py", line 12, in 
    from .cartogramprocessingalgorithm import CartogramProcessingAlgorithm
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramprocessingalgorithm.py", line 24, in 
    from .cartogramfeatures import CartogramFeatures
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramfeatures.py", line 31
    def _cache(user_function, /):
                              ^
SyntaxError: invalid syntax

Python-Version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS-Version: 3.16.6-Hannover Hannover, bfd36fddc9 

Python-Pfad:
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.16/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS3~1.16\apps\Python37
C:\PROGRA~1\QGIS3~1.16\apps\Python37\Scripts
C:\Program Files\QGIS 3.16\bin\python37.zip
C:\PROGRA~1\QGIS3~1.16\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib
C:\Program Files\QGIS 3.16\bin
C:\Users\USER\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\site-packages\Pythonwin
C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\USER\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms

On one machine the installation works, but when I start a process it just doesn't do anything. (the task is at 0% processor usage) and there is no change or process, that also happens when I start it from the toolbox.

Am I missing something here? It seems I am the only or first one to have this trouble, I didn't find a similar thread anywhere.

Anyways I would be very glad if you could help me, maybe (hopefully) it's something obvious and I am just an idiot.
Thanks in advance.
KaR

**Comment by christophfink** [comment]
Hi!

It’s the old Python version your QGIS is using. It should not be an issue with newer versions of QGIS, that’s a bit puzzling - how did you install QGIS (OSGEO4W, standalone installer)?

I have a fairly easy fix (I think), could you please test it:

Can you open `C:/Users/USER/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\cartogram3\lib\cartogramfeatures.py` in a text editor, and edit line 31 to now read:

```
    def _cache(user_function):
```

(That’s, remove the comma, space and slash in the argument list. This is a feature introduced in Python 3.8, only - I missed that it came so recently)

If this works for you, I would submit a corrected version to the QGIS plugin repository (but that always takes a few days for admins to approve a new plugin version). Thanks for you help!

**Comment by voltameeak** [comment]
Hi, 
that fix worked brilliantly. No more error message and the process went through nicely. Thank you very much for your quick and helpful response.
FYI: installation worked before the fix on QGIS 3.24 but the process just doesn't start, Thats probably another issue, but it works now on older QGIS Versions so I am happy with that.

**Comment by christophfink** [comment]
Fantastic! I submitted a new version to the QGIS plugin repository to fix this issue. Thanks for your help!

In case you run into the 3.24 problem, again, could you please open a new issue? Thanks!
